#!/bin/bash
echo "packageDeployPath= $packageDeployPath"
echo "packageSkip= $packageSkip"
echo "packageMaintainer= $packageMaintainer"
echo "packageHomepage= $packageHomepage"
echo "packageName= $packageName"
echo "packageArchitecture= $packageArchitecture"
echo "packageDepends= $packageDepends"
echo "packageDescription= $packageDescription"
echo "packageMoreDescription= $packageMoreDescription"
echo "packageVersion= $packageVersion"
echo "packageSource= $packageSource"
echo "tomcatSkip= $tomcatSkip"
echo "tomcatVersion= $tomcatVersion"
echo "excludeJar= $excludeJar"
echo "catalinaOption= $catalinaOption"
echo "mysqlSkip= $mysqlSkip"
echo "mysqlUsername= $mysqlUsername"
echo "mysqlPassword= $mysqlPassword"
echo "mysqlBinPath= $mysqlBinPath"
echo "sqlFileName= $sqlFileName"
echo "commonDate= $commonDate"
echo "needClean= $needClean"
echo "databaseBaseName= $databaseBaseName"
echo "databaseOldName= $databaseOldName"
echo "tomcatNewPort= $tomcatNewPort"
echo "tomcatPreviousPort= $tomcatPreviousPort"

